version: '2'
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../etc/nginx:/etc/nginx
      - ../app/web:/app/web
    links:
      - php5-fpm:php-fpm
    depends_on:
      - php5-fpm
  php5-fpm:
    image: "registry.cn-hangzhou.aliyuncs.com/zfuming/php5-dev:latest"
    volumes:
      - ../app/web:/app/web
      - ../etc/php:/usr/local/etc/php
      - ../etc/php-fpm:/usr/local/etc
    depends_on:
      - mysql
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      #- ../etc/mysql:/etc/mysql/conf.d
      #- ../etc/mysql/my.cnf:/etc/my.cnf
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
